Upgrade of spock-core to 2.0-groovy-3.0 to fix the following error:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileFunctionalTestGroovy'.
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-nio is loaded in version 3.0.8 and you are trying to load version 2.5.4
	... 28 more